version: '2'
services:
  r-serve:
    container_name: r-serve
    image: r-serve:latest
    build: ./r-serve
    restart: always
    networks:
      - backend-network
    dns: 8.8.8.8
    ports:
      - "6311:6311"
  rservices:
    container_name: rservices
    image: rservices:latest
    build: ./rservices
    restart: always
    depends_on:
      - r-serve
    links:
      - r-serve
    networks:
      - backend-network
    dns:
      - 8.8.8.8
    ports:
      - "8080:8080"
      - "5080:5080"
networks:
  backend-network:
    driver: bridge